version: '3'

services:
  tele:
    image: mlan/asterisk
    network_mode: bridge # Only here to help testing
    cap_add:
      - sys_ptrace       # Only here to help testing
      - net_admin
      - net_raw
    ports:
      - "${SMS_PORT-8080}:80"
      - "5060:5060/udp"
      - "5060:5060"
      - "5061:5061"
      - "10000-10099:10000-10099/udp"
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}
      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
    volumes:
      - tele-conf:/srv

volumes:
  tele-conf:
